# States
FOLLOWER = 'FOLLOWER'
CANDIDATE = 'CANDIDATE'
LEADER = 'LEADER'

# Requests
APPEND_RPC = 'APPEND_RPC'
VOTE_REQUEST = 'VOTE_REQUEST'
VOTE_ACK = 'VOTE_ACK'
CONVERT_FOLLOWER = 'CONVERT_FOLLOWER'
TIMEOUT = 'TIMEOUT'
SHUTDOWN = 'SHUTDOWN'
LEADER_INFO = 'LEADER_INFO'
